obj-$(CONFIG_FIRMWARE_ALTERA_SERIAL) += altera_serial.o
obj-$(CONFIG_FIRMWARE_ALTERA_SOCFPGA) += socfpga.o
obj-$(CONFIG_FIRMWARE_NETX4000_XC) += netx4000-xc.o
netx4000-xc-y := netx4000-xc-main.o netx4000-xc-hal.o
