#!/bin/sh

func=$1

# func: image
# If available, sets the image path variable to the image (e.g. fitImage, kernel ...)
if [ "$func" = "image" ]; then
	mp=$2
	path=$3
        if [ -L $mp$path ]; then
                readlink -f $mp$path image
                readlink $mp$path link
                [ "$image" = "$link" ] && image=$mp$image
        elif [ -f $mp$path ]; then
                image="$mp$path"
        fi
fi

# func: initrd
# If available, sets the initrd path variable to the initrd
if [ "$func" = "initrd" ]; then
	mp=$2
	path=$3
	if [ -L $mp$path ]; then
                readlink -f $mp$path initrd
                readlink $mp$path link
                [ "$initrd" = "$link" ] && initrd=$mp$initrd
        elif [ -f $mp$path ]; then
                initrd="$mp$path"
        fi
fi

# func: oftree
# If available, sets the oftree path variable to the oftree
if [ "$func" = "oftree" ]; then
	mp=$2
	path=$3
        if [ -L $mp$path ]; then
                readlink -f $mp$path oftree
                readlink $mp$path link
                [ "$oftree" = "$link" ] && oftree=$mp$oftree
        elif [ -f $mp$path ]; then
                oftree="$mp$path"
        fi
fi
