#!/bin/sh

linux_dev=$1

# image: fitImage, zImage (mandatory)
image=""
[ -z "$image" ] && . /env/boot/_set_boot_env image /mnt/part1 /boot/fitImage
[ -z "$image" ] && . /env/boot/_set_boot_env image /mnt/part1 /fitImage
[ -z "$image" ] && . /env/boot/_set_boot_env image /mnt/part1 /boot/zImage
[ -z "$image" ] && . /env/boot/_set_boot_env image /mnt/part1 /zImage
[ -z "$image" ] && . /env/boot/_set_boot_env image /mnt/part2 /boot/fitImage
[ -z "$image" ] && . /env/boot/_set_boot_env image /mnt/part2 /fitImage
[ -z "$image" ] && . /env/boot/_set_boot_env image /mnt/part2 /boot/zImage
[ -z "$image" ] && . /env/boot/_set_boot_env image /mnt/part2 /zImage
[ -z "$image" ] && . /env/boot/_set_boot_env image /mnt/part1 /vmlinuz
[ -z "$image" ] && . /env/boot/_set_boot_env image /mnt/part2 /vmlinuz
[ -z "$image" ] && exit 1

# rootfs: partition, image file (mandatory)
root=""
if [ -L /mnt/part1/sbin/init -o -f /mnt/part1/sbin/init ]; then
	root="rootwait root=${linux_dev}1 rw"
elif [ -L /mnt/part2/sbin/init -o -f /mnt/part2/sbin/init ]; then
	root="rootwait root=${linux_dev}2 rw"
elif [ -L /mnt/part1/rootfs.img -o -f /mnt/part1/rootfs.img ]; then
	root="rootwait root=${linux_dev}1/rootfs.img rw"
elif [ -L /mnt/part2/rootfs.img -o -f /mnt/part2/rootfs.img ]; then
	root="rootwait root=${linux_dev}2/rootfs.img rw"
else
	exit 1
fi

# initrd (optional)
initrd=""
[ -z "$initrd" ] && . /env/boot/_set_boot_env initrd /mnt/part1 /boot/initramfs
[ -z "$initrd" ] && . /env/boot/_set_boot_env initrd /mnt/part1 /initramfs
[ -z "$initrd" ] && . /env/boot/_set_boot_env initrd /mnt/part2 /boot/initramfs
[ -z "$initrd" ] && . /env/boot/_set_boot_env initrd /mnt/part2 /initramfs

# oftree (optional)
oftree=""
[ -z "$oftree" ] && . /env/boot/_set_boot_env oftree /mnt/part1 /boot/oftree
[ -z "$oftree" ] && . /env/boot/_set_boot_env oftree /mnt/part1 /oftree
[ -z "$oftree" ] && . /env/boot/_set_boot_env oftree /mnt/part2 /boot/oftree
[ -z "$oftree" ] && . /env/boot/_set_boot_env oftree /mnt/part2 /oftree

global.bootm.image="$image"
global.bootm.initrd="$initrd"
global.bootm.oftree="$oftree"
global.linux.bootargs.dyn.root="$root"

exit 0
