#!/bin/sh

MP1="/mnt/part1"
MP2="/mnt/part2"

usb
if [ -e /dev/disk1.0 ]; then
	mkdir -p $MP1
	mount /dev/disk1.0 $MP1 && echo "Succesfully mounted usb (part1) to" $MP1 || echo "Unable to mount usb (part2)"
fi

if [ -e /dev/disk1.1 ]; then
	mkdir -p $MP2
	mount /dev/disk1.1 $MP2 && echo "Succesfully mounted usb (part2) to" $MP2 || echo "Unable to mount usb (part2)"
fi

/env/boot/set_boot_env "/dev/sda"

if [ -z "$global.bootm.image" -o -z "$global.linux.bootargs.dyn.root" ]; then
	if [ -d $MP1 ]; then umount $MP1; rm $MP1; fi
	if [ -d $MP2 ]; then umount $MP2; rm $MP2; fi
	exit 1
fi

exit 0
